sudo: required
services:
    - docker

before_install:
    - docker build -t adrmulyawan/react-test -f ./client/Dockerfile.dev
    - docker build react-docker1

script:
    - docker run adrmulyawan/react-test npm test -- --coverage

after_success:
    - docker build -t adrmulyawan/multi-client ./client
    - docker build -t adrmulyawan/multi-nginx ./nginx
    - docker build -t adrmulyawan/multi-server ./server
    - docker build -t adrmulyawan/multi-worker ./worker

    #Login into docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
    
    # Take those images and push them to docker hub
    - docker push adrmulyawan/multi-client
    - docker push adrmulyawan/multi-nginx
    - docker push adrmulyawan/multi-server
    - docker push adrmulyawan/multi-worker